# Generated by Django 4.2.5 on 2023-09-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_proyect_options_proyect_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyect',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Url del proyecto'),
        ),
    ]
